- sql/promscale--0.1--0.1.1.sql
- sql/promscale--0.1.1.sql
- sql/promscale--0.1.sql
Safe to do because this extension has never been published under this name
> Change telemetry prefix

- Cargo.toml
The postgres extension library we use has the option to use cached rust bindings to the postgres headers in order to improve compile times. This was only supposed to be used for development, as using it in other circumstances would carry a risk of using stale headers. Unfortunately, it looks like the commit changing that default got lost so this commit performs that change in our makefile.
> Build headers by default

- Cargo.lock
- Cargo.toml
- sql/promscale--0.1.2--0.1.3-beta.sql
- sql/promscale--0.1.3-beta.sql
- src/lib.rs
- src/type_builder.rs
a vector selector aggregate has the same semantics as parse.VectorSelector processing
in Prometheus. Namely, for all timestamps ts in the series:
ts := ev.startTimestamp; ts <= ev.endTimestamp; ts += ev.interval
we return the last sample.value such that the time sample.time <= ts and sample.time >= ts-lookback.
if such a sample doesn't exist return NULL (None).
thus, the vector selector returns a regular series of values corresponding to all the points in the
ts series above.
Note that for performance, this aggregate is parallel-izable, combinable, and does not expect ordered inputs.
Relies on #14
> Add vectorSelector

- Readme.md
Updated the Readme with more detailed, step-by-step instructions for getting a working instance of promscale with the promscale_extension compiled from source and installed in the database.
> Add more detailed installation instructions

- .github/workflows/ci.yaml
Add GHA workflow to run tests for the extension against Postgres 14. We can add support for other Postgres versions once we've sorted out how to handle test output differences that currently cause the tests to fail when run under versions other than 14.
> ci: run tests on pull_request events

- Makefile
- promscale.control
PGX added support to use the cargo version as the extension version. To
enable this, the default_version in the .control file must be replaced
with `@CARGO_VERSION@`.
> Derive extension version from cargo crate version

- .gitignore
These entries became irrelevant when we stopped compiling and linking C
and Rust sources manually.
> Remove irrelevant .gitignore entries

- Cargo.lock
- src/aggregates/prom_delta.rs
- src/aggregates/prom_increase.rs
- src/aggregates/prom_rate.rs
- src/aggregates/vector_selector.rs
- src/raw.rs
pgx used to emit pg_sys::TimestampTz as BIGINT in SQL. This has been
fixed upstream to emit TIMESTAMP WITH TIME ZONE. With that upstream
change, we can jettison our custom TimestampTz wrapper.
> Use pg_sys::TimestampTz in place of custom TimestampTz wrapper

- Cargo.lock
- Dockerfile
If the revision is not specified, then docker can cache the build step
and get stuck on an old revision of the branch.
> Specify desired pgx revision in Dockerfile

- Dockerfile
This is a common rust/cargo trick: create a new empty project with the
actual Cargo.{toml,lock} files and build it. This pre-builds all of the
dependencies, a lot of which can be reused in the following steps,
reducing the amount of code compiled when updating source files.
On my machine it reduces rebuild time from ~250s to 80s.
> Improve docker image build time

- DockerMakefile
- Dockerfile
- sql/promscale--0.1--0.1.1.sql
- sql/promscale--0.1.1.sql
- sql/promscale--0.1.2--0.1.3-beta.sql
- sql/promscale--0.1.3-beta.sql
- sql/promscale--0.1.sql
This change fixes a privilege escalation vulnerability, by which an
unprivileged user precreates a function or operator which is later
executed from a privileged context.
Additionally, this change uses the fully-qualified name for functions,
tables, and operators which are used throughout the extension.
> Fix privilege escalation issue

- .gitignore
- Cargo.lock
- Cargo.toml
- Dockerfile
- build.rs
- migration/migration-table.sql
- migration/migration/012-tracing-well-known-tags.sql
- src/schema/mod.rs
- src/schema/sql.rs
- templates/idempotent-wrapper.sql
- templates/migration-wrapper.sql
This change introduces a build script which wraps the contents of each
SQL file in the `migrations` directory in a DO block which conditionally
applies the migration if it has not yet been applied to the database.
The build script outputs its contents to `migration.sql`, which in turn
is included in the generated SQL which pgx outputs.
> Wrap migration SQL in migration do-block, emit with pgx

- .github/workflows/docker.yaml
- Makefile
This is in line with recent changes in the promscale repo: https://github.com/timescale/promscale/pull/1199
> Remove timescaledb 1.x docker image build

- promscale.control
Having the extension marked as trusted allows it to be installed by
non-superuser users.
> Mark extension as trusted

- Dockerfile.quick
- Makefile
To use, first run: `make docker-image-ts2-14`. Then you can edit the SQL
and run `make docker-quick-ts2-14`.
> Provide docker-quick-ts2-{12,13,14} target for quick iteration on SQL

- .github/workflows/docker.yaml
- Dockerfile.quick
- Makefile
Now that we're no longer building a timescaledb 1 image, the ts2/2
specifier is not required.
> Simplify docker image make targets

- migration/idempotent/007-tracing-tags.sql
The signature of the GRANT EXECUTE doesn't match up with the function
definition.
> Fix incorrect GRANT EXECUTE

- migration/idempotent/001-base.sql
- migration/idempotent/003-matcher-functions.sql
- migration/idempotent/010-telemetry.sql
- migration/migration/001-utils.sql
- migration/migration/006-matcher-operators.sql
- migration/migration/010-tables-exemplar.sql
With the removal of default search paths from the extension SQL, some
objects must be fully-qualified to work correctly.
> Fully-qualify objects in hand-written SQL

- Dockerfile
- Dockerfile.quick
- Makefile
- create-upgrade-symlinks.sh
- promscale.control
When a new extension version is published, we require both a SQL schema
file for the new version (e.g. promscale--0.8.0.sql), as well as an
upgrade schema file (e.g. promscale--0.7.0--0.8.0.sql).
Because we're versioning the shared object, we actually require an
upgrade schema file for every previously-published version to the new
version (otherwise function definitions reference a .so which is not
present).
The fact that our major-version SQL schema file has an internal
migration mechanism making it effectively idempotent means that we can
reuse the major-version SQL schema file as the upgrade file to that
version.
This commit adds machinery to automatically create symlinks pointing to
the major-version SQL schema.
> Create version upgrade symlinks

- sql/promscale--0.0.0.sql
This is the 0.0.0 version script, a.k.a. the "takeover" script. When upgrading an existing installation from pre-0.5.0 to 0.5.0 and above, this script is run as a part of the process. The extension is dropped (if exists) and then version 0.0.0 of the extension is installed, which runs this script. Next, the extension is updated to 0.5.0 or higher.
The script adds existing database objects to the extension, changes privileges and ownership, and makes certain tables "config" tables such that they get pg_dumped.
Another PR will handle the "fresh install" path. Unfortunately, I don't expect the upgrade tests to pass with the two paths split like that. Furthermore, many of the e2e tests may also fail pending the idempotent changes which I assume will come with the "fresh install" PR. If this …
> 0.0.0 script to transition an existing installation into the new way

- Makefile
- migration/idempotent/001-base.sql
- migration/migration/002-utils.sql
The commands stored in the remote_commands table are executed by the extension/superuser. Making execute_everywhere security definer is a vulnerability. Remove the security definer.
Also, adjusted the "quick" targets in the Makefile so that they tag the image with all the same tags the "non-quick" targets do.
> Remove SECURITY DEFINER from _prom_catalog.execute_everywhere

- Cargo.lock
- Cargo.toml
- src/iterable_jsonb.rs
- src/jsonb_digest.rs
- src/lib.rs
- src/raw.rs
A custom SHA512 based JSONB digest.
Save for hash collisions, for any pair of `j1` and `j2` the statement `SELECT jsonb_digest(j1) = jsonb_digest(j2)` is true iff `j1 == j2` are _semantically_ equivalent.
There is a couple of alternatives, unfortunately neither should be used in a UNIQUE index.
`pg_catalog.sha512(json_value::text::bytea)` has two drawbacks:
- There isn't enough control over `jsonb` -> `text` conversion.
Although, the existing implementation relies on the same mechanism
as `jsonb_digest` and should always keep object keys in the fixed
order, there's no way to explicitly set specifics of its behaviour
like indentation or white-space padding.
- JSONB stores all numeric values in PostgreSQL `numeric` type.
It's not just precise, it accurately preserves trailing fractional …
> SHA512 based JSONB digest function

- .github/workflows/docker.yaml
- Makefile
- alpine.Dockerfile
- ha.Dockerfile
- quick.Dockerfile
The environment variables used to control which version of postgres to
build for were not aligned between the alpine and ha images, and not
aligned with the docker workflow. This meant that all images were built
against pg14, but tagged with different PG versions.
> Fix docker image build

- migration/idempotent/007-tracing-tags.sql
- migration/idempotent/008-tracing-functions.sql
- migration/idempotent/013-apply-config.sql
- migration/migration/015-tracing-large-tags-fix.sql
- src/lib.rs
This addresses #128 by replacing `value` attribute within the UNIQUE constraint with `sha512` hash of its textual representation.
I ran the following SQL as a microbenchmark:
```sql
SELECT put_tag('service.name', n::text::jsonb, resource_tag_type())
FROM generate_series(1, 20000) AS gs (n)
```
and
```sql
SELECT get_tag_map(('{"service.name": ' || n::text || '}')::jsonb)
FROM generate_series(1, 20000) AS gs (n)
```
~There doesn't seem to be a significant performance difference on the insertion path. Unmodified get_tag_map became roughly twice as slow, so I had to alter it as well. This hints at possible performance degradation elsewhere.~ 
I think I was able to chase down all functions that relied on an index covering `(key, value)`  and augmented these places with an additional check …
> Fix for uniqueness constraint on large tag values.

- .dockerignore
- .github/workflows/docker.yaml
- .gitignore
- Cargo.lock
- Cargo.toml
- alpine.Dockerfile
- e2e/Cargo.toml
- e2e/README.md
- e2e/build.rs
- e2e/testdata/info_view.sql
- e2e/testdata/support.sql
- e2e/testdata/views.sql
- e2e/tests/common/mod.rs
- e2e/tests/golden-tests.rs
- e2e/tests/snapshots/golden_tests__golden_test_testdata_info_view_sql.snap
- e2e/tests/snapshots/golden_tests__golden_test_testdata_support_sql.snap
- e2e/tests/snapshots/golden_tests__golden_test_testdata_views_sql.snap
- e2e/tests/test.rs
- ha.Dockerfile
This change adds a dedicated e2e workspace which can be used to run
end-to-end tests against the promscale extension.
This change also also ports the golden SQL tests from the promscale
repository.
> Add e2e test framework and port golden SQL tests

- migration/idempotent/001-base.sql
Currently, we are using `timescaledb_information.chunks` view which can be
slow for systems that have a lot of metrics. By switching to using catalog
tables directly, we can improve the performance of queries used there.
> Optimize maintenance jobs by using TS catalog tables

- Makefile
The sql generator will by default use the develop profile but
since pgx package uses the release profile it is better to use
the release profile for the sql generation too. Otherwise,
everything needs to be compiled two times.
> Optimize builds

- .github/workflows/ci.yaml
- .github/workflows/docker.yaml
- .gitignore
- Makefile
- alpine.Dockerfile
- build.rs
- ha.Dockerfile
- migration/migration/003-users.sql
- sql/promscale--0.0.0.sql
- src/aggregates/vector_selector.rs
- src/support.rs
- templates/promscale.control
- `promscale.control` is generated via `build.rs` based on pg version
- CI tests and image builds are re-enabled on pg12
- Migrations, involving `@extowner@`, had to be altered to be compatible with pg12.
- Some tests had to be generalized to pass on both pg14 and pg12
Addresses #109 
Upgrade and e2e tests pass https://github.com/timescale/promscale/pull/1287
> Make trusted extension optional (for PG12)

- migration/idempotent/001-base.sql
A couple of typos in this function broke it when used with two-step
continuous aggregates. A companion change in the promscale repository
adds a test to exercise this code path [1].
[1]: https://github.com/timescale/promscale/pull/1294
> Fix `prom_api.reset_metric_retention_period`

- e2e/tests/test.rs
Before timescaledb 2.6.1 it was not possible to drop the extension. Now
that we've bumped to 2.6.1 we can add a test case.
Fixes #95
> Add DROP EXTENSION to test

- e2e/tests/snapshots/golden_tests__golden_test_testdata_info_view_sql.snap
- e2e/tests/snapshots/golden_tests__golden_test_testdata_support_sql.snap
- migration/idempotent/009-tracing-views.sql
- migration/idempotent/014-trace-id-functions.sql
- migration/migration/015-tracing-compression.sql
Using domain type didn't play nicely with TimescaleDB planner: some pushdowns
were not working well on compressed data (https://github.com/timescale/timescaledb/issues/4179). 
Here we add custom type that wrapps around PG UUID type.
The idea is to later on customize this type - eg. string representation.
Since trace_id is used for data partitioning this change is not backwards
compatible.
Closes https://github.com/timescale/promscale_extension/issues/134
> Custom type for trace_id

- migration/migration/015-tracing-compression.sql
We follow the rule of ordering columns  in descending order based on
data type size.
8 bytes -> 4 bytes -> 2 bytes -> variable lenght types.
This should result in minimal alignment padding meaning that we
will be more storage efficient.
> Better data alignment for tracing tables

- .gitignore
- build.rs
- migration/README.md
- migration/bootstrap/000-migration-table.sql
- migration/bootstrap/001-create-ext-schema.sql
- sql/promscale--0.0.0.sql
- src/aggregates/gapfill_delta.rs
- src/aggregates/mod.rs
- src/aggregates/prom_delta.rs
- src/aggregates/prom_increase.rs
- src/aggregates/prom_rate.rs
- src/aggregates/vector_selector.rs
- src/jsonb_digest.rs
- src/schema.rs
- src/support.rs
- src/util.rs
- templates/idempotent-wrapper.sql
- templates/migration-wrapper.sql
- templates/promscale.control
Because the extension was declared as non-relocatable, and in the schema
`_prom_ext`, it was possible to have that schema (and objects in it)
created before the extension install script is run. This opened the
extension up to precreation attacks.
This change takes a number of measures to mitigate that.
- We configure the schema to `public`, which allows the extension to
control the creation of the `_prom_ext` schema.
- We add a `bootstrap` migration script which is run before the pgx
generated SQL, which creates the `_prom_ext` schema.
- We tell pgx to put all generated objects in the `_prom_ext` schema.
> Ensure that _prom_ext schema created safely

- migration/idempotent/001-base.sql
This was missed previously because the SQL is embedded in a string.
> Fully schema-qualify operator

- migration/idempotent/001-base.sql
Postgres doesn't short-circuit evaluate `IF cond_a AND cond_b` when
`cond_a` is false, so it to evaluates `cond_b`. In this case the
evaluation of `cond_b` will fail when `cond_a` is false.
> Fix `safe_approximate_row_count` when timescaledb not present

- .github/workflows/ci.yaml
- .github/workflows/docker.yaml
- .github/workflows/lint.yaml
The pgspot [1] tool is used to spot vulnerabilities in PostgreSQL
extension scripts.
[1]: github.com/timescale/pgspot
> Add pgspot lint check

- e2e/testdata/support.sql
- e2e/tests/snapshots/golden_tests__golden_test_testdata_support_sql.snap
- migration/migration/004-schemas.sql
- migration/migration/017-set-search-path.sql
We assume that most users are going to be installing promscale into a
database which has been setup specifically for promscale. Further, we
assume that without having these search paths available by default,
users will run into trouble with not being able to find the tables,
functions, and operators which promscale provides.
Hence, we set the database-wide default search_path to contain all of
our "public" schemas (private schemas are prefixed with an underscore).
> Set database-wide default search_path

- migration/incremental/018-grant-prom-roles.sql
It seems that when using pgextwlist extension the current_user is set to
postgres meaning that roles would not be granted to the user trying to
install the extension.
> Grant prom roles to session user

- migration/incremental/015-tracing-compression.sql
These two types are binary coercible and we can cast without a function.
This will enable:
`SELECT '00000000-0000-0000-1763-6d7b3258c7bf'::uuid::ps_trace.trace_id`
`SELECT '00000000-0000-0000-1763-6d7b3258c7bf'::ps_trace.trace_id::uuid`
> Cast between trace_id and uuid 

- migration/incremental/019-jit-off.sql
PG JIT compilation doesn't play nicely with TimescaleDB planner
and can cause a huge slowdown for specific queries so we are turning it off.
We might revisit this once JIT issues are fixed in TimescaleDB. (it might not be all TimescaleDB fault as PG itself can perform poorly when JIT is on for specific queries)
Setting JIT on database level will also disable it for 3rd party apps connecting to database (which is a good thing imho)
Related TimescaleDB issue https://github.com/timescale/timescaledb/issues/4222
> JIT off by default

- .github/workflows/lint.yaml
- migration/README.md
- migration/bootstrap/000-migration-table.sql
- migration/idempotent/001-base.sql
- migration/idempotent/004-ha.sql
- migration/idempotent/005-metric-metadata.sql
- migration/idempotent/006-exemplar.sql
- migration/idempotent/007-tracing-tags.sql
- migration/idempotent/008-tracing-functions.sql
- migration/idempotent/010-telemetry.sql
- migration/idempotent/011-maintenance.sql
- migration/incremental/002-utils.sql
- migration/incremental/008-install-uda.sql
- sql/promscale--0.0.0.sql
When `pg_temp` is not specified explicitly in the `search_path`, it is
_prepended_ to the existing `search_path`. This allows for an attacker
to shadow tables in the `pg_catalog` schema, allowing them to trick
scripts which rely on the contents of certain system tables (e.g.
`pg_catalog.pg_user`.
> Fix insecure search_path in migration scripts

- .github/workflows/release.yaml
On pre-release:
- send packages to the timescaledb-exp package cloud repo
- mark the github release as pre-release
> Handle pre-release releases

- e2e/scripts/post-snapshot.sql
- e2e/scripts/pre-dump.sql
- migration/incremental/015-tracing-compression.sql
- src/lib.rs
This makes the enum names much more user-friendly on the SQL level.
We made them lowercase and removed the prefix.
```
SELECT
*
FROM ps_trace.span
WHERE start_time > NOW() - INTERVAL '30m'
AND status_code = 'STATUS_CODE_ERROR'
```
Now becomes
```
SELECT
*
FROM ps_trace.span
WHERE start_time > NOW() - INTERVAL '30m'
AND status_code = 'error'
```
> Rename tracing enums

- .github/workflows/release.yaml
- tools/package
The commands to parse `cargo metadata` didn't handle cargo workspaces
correctly, so were pulling out the version of the `e2e` package instead
of the `promscale` package.
> Correctly determine package version

- .github/workflows/release.yaml
For package_cloud centos/7 should have the tag el/7.
> Fix package cloud tag

- .github/workflows/ci.yaml
- .github/workflows/docker.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- alpine.Dockerfile
- dist/deb.dockerfile
- dist/rpm.dockerfile
- ha.Dockerfile
This change integrates a number of improvements to caching in our build
pipelines. The results of different comparisons can be seen here: [1].
Overall, testing changes to caching is _hard_ because there are a lot of
different caching mechanisms in place. We already use caching in Docker
layers, and for "local" (not in Docker) Rust compilation. These existing
mechanisms can confound the result of a run.
The main change is integrating `sccache` into all aspects of the build.
We configure it to use an S3 bucket as the backing store for cached
artifacts, which allows the cache to be persisted over multiple CI runs.
The following is a breakdown of the major experiments and their results:
- ci.yaml
This workflow consists primarily of Rust compilation directly on the
github actions runner. Here …
> Improve build caching

- migration/incremental/020-series-partitions.sql
The old query took a long time on a DB with lots of data. The
renaming itself is and was quick. It's just the query to get
the list of indexes used to be slow.
> Fix migration query speed

- migration/incremental/015-tracing-redesign.sql
This is needed for lookups by ID such as in the denormalize function.
This used to exist (without the include) on the partitions but
we forgot about that when we de-partitioned the table.
> Add primary key to tag table

- migration/incremental/003-users.sql
- sql/promscale--0.0.0.sql
Needed to support pgextwlist deployments. Session_user
should replace extowner everywhere with this commit.
> Switch owner assignment to session_user

- .github/workflows/release.yaml
- Makefile
- tools/package
Debian/Ubuntu has the convention that package names do not contain
underscores [1]. While Fedora allows underscores, it states that dashes
should be used in preference of underscores [2].
[1]: https://www.debian.org/doc/debian-policy/ch-controlfields.html#source
[2]: https://fedoraproject.org/wiki/Packaging:Naming?rd=Packaging:NamingGuidelines#General_Naming
> Create packages as `promscale-extension`

- README.md
These instructions will be correct once we publish the packages to packagecloud, i.e. when we release 0.5.0 proper.
> Update packaged install instructions

- migration/idempotent/008-tracing-functions.sql
- src/lib.rs
Creates a temporary table (if it doesn't exist), suitable for tracing data ingestion.
Suppresses corresponding DDL logging, otherwise, the PG log may get unnecessarily verbose.
Addresses https://github.com/timescale/promscale/pull/1333
> Support for reuse temp table for trace ingest 

- migration/idempotent/001-base.sql
- migration/incremental/024-adjust_autovacuum.sql
On uncompressed tables
- set the threshold and scale_factors higher to make
less aggressive
On compressed tables
- make freeze run on every vacuum
- make sure vacuum runs quickly after creation by decreasing
threshold and scale_factor
Fix settings on PG13 and 14 by using the `_insert_` version of settings.
> Adjust autovacuum settings

- e2e/testdata/tag_map.sql
- e2e/tests/snapshots/golden_tests__testdata__tag_map.sql.snap
- migration/idempotent/007-tracing-tags.sql
- Add missing operators
- Add opclass so pg can correctly find `=` operator for the type thus enabling `group by` and `distinct` queries
- Fix/adjust tests
- Some minor fixes in tests
- Bug fixes in idempotent scripts (*please review thoroughly*)
> Fix tag_v type missing some operators and opclass

- Cargo.lock
- e2e/Cargo.toml
- e2e/tests/incremental-freeze-test.rs
The sql scripts in migration/incremental/ are not idempotent. They are meant to be run once
and only once on any given promscale installation. We track whether these files have
been applied in the _ps_catalog.migration table. Once we have released a version of
promscale, all the incremental scripts are considered frozen. They have been applied to
databases in the wild, and we don't want to create a situation in which some databases were
created using one version of a script, while others used a different version.
This test is meant to keep us from accidentally changing an incremental file after it has
been released. When cutting a new release, append to the list of files below the filenames
and MD5 hashes of all the new files going out with that release.
> Ensure that frozen incremental files are not modified

- README.md
The readme currently states that extension is not mandatory
> Indicate the promscale extension is required now

- Makefile
- README.md
- We forgot to update the version in the documentation
- The installation broke between 0.3.0 and 0.5.0. The reason is that the
recommended way to install Rust/rustup is in a per-user directory.
This means that invoking anything via sudo doesn't have Rust available
to it. Instead of trying to (effectively) `sudo cargo ...`, separate
out `make` and `make install`, so that `sudo make install` works.
Fixes #311
> Fix compile from source

- migration/idempotent/001-base.sql
- migration/idempotent/006-exemplar.sql
- migration/idempotent/013-tracing-maintenance.sql
Since NAME type uses C collation it confuses PG planner and results in non
optimal query plans (not using indexes where it should).
We switch to use TEXT for function IN arguments and that results in picking
optimal query plans.
Switch shouldn't cause any harm
since internally both types are stored the same just
NAME is limited to 63-chars, but TEXT has no limits.
An example of non-optimal query plan:
```
Aggregate  (cost=298493.79..298494.05 rows=1 width=128) (actual time=2816.778..2816.780 rows=1 loops=1)
CTE cte
->  Result  (cost=298490.80..298493.43 rows=10 width=72) (actual time=2816.760..2816.764 rows=13 loops=1)
->  Sort  (cost=298490.80..298490.83 rows=10 width=72) (actual time=2816.759..2816.761 rows=13 loops=1)
Sort Key: kv.key COLLATE "C", kv.value COLLATE "C"
Sort Method: …
```
> Use text instead of name for function args

- .gitignore
The scripts in the /sql directory are automatically generated. These do not need to be committed until we cut a release. It's a bit annoying to have git call out changes to these files in the meantime, so ignore them.
> gitignore the sql directory

- docs/sql-api.md
- migration/idempotent/001-base.sql
- migration/incremental/026-remove-name-param.sql
We changed the signatures of some functions and procedures. We changed the data types from `name` to `text`. We did so with `create or replace function`. Since the signature changed, postgres ran this as a `create` and we ended up with two versions of each function/procedure. This adds a migration that drops the old versions.
> Drop old versions of func/proc where signature changed

- e2e/testdata/dummy-test.sql
- e2e/testdata/scripts/pgtap-1.2.0.sql
- e2e/tests/common/mod.rs
- e2e/tests/snapshots/golden_tests__testdata__dummy-test.sql.snap
This offers a simple way to write tests in SQL which assert assert,
offering more power than golden-file tests.
Note: the current implementation _does_ use snapshot tests as a simple
mechanism for validating that the test is correct. Ideally we would have
a way to parse the pgTAP output and pass it on to the rust test harness.
> Add test harness with pgTAP helper functions

- Cargo.lock
- e2e/Cargo.toml
- e2e/tests/incremental-freeze-test.rs
Performing a string test allows us to more easily determine the new hash
when it needs to be updated.
Before this change:
```
thread 'incremental_freeze_test' panicked at 'assertion failed: `(left == right)`
left: `[86, 36, 242, 147, 64, 114, 86, 184, 250, 150, 192, 104, 254, 157, 86, 133]`,
right: `[138, 149, 52, 207, 133, 52, 192, 203, 107, 47, 147, 154, 168, 223, 50, 194]`: migration/incremental/001-extension.sql is frozen but appears to have been modified', e2e/tests/incremental-freeze-test.rs:109:9
```
After this change:
```
thread 'incremental_freeze_test' panicked at 'assertion failed: `(left == right)`
left: `"8a9534cf8534c0cb6b2f939aa8df32c2"`,
right: `"8a9534cf8534c0cb6b2f939aa8df0000"`: migration/incremental/001-extension.sql is frozen but appears to have been modified', …
```
> Use string comparison in incremental freeze test

- build.rs
- migration/bootstrap/002-stop-bgw.sql
- sql/promscale--0.0.0.sql
This commit stops bgws while upgrading the Promscale extension.
This prevents lock contention between jobs and upgrades and thus
seems safer.
> Stop all background workers for the duration of the upgrade

- migration/idempotent/014-extension-type-functions.sql
These type-related extension functions are not emitted by PGX, so must
be added to our idempotent scripts in order to point the functions at
the most recent version of our versioned extension binary.
> Update function definitions for type-related PGX functions

- Makefile
- alpine.Dockerfile
The latest version of timescaledb is 2.7.0, but our Makefile is still building with 2.6.x. Fix this.
> Bump the version of timescaledb to 2.7.0 in our Makefile

- Makefile
Using `cp -a` messes with attributes of higher-level directories, which
is not what we want.
> Fix install target

- README.md
- docs/sql-api.md
- migration/idempotent/007-tracing-tags.sql
- migration/idempotent/008-tracing-functions.sql
- migration/idempotent/011-maintenance.sql
- migration/idempotent/012-trace-id-functions.sql
- This PR partially addresses #159 by adding SQL comments to functions and procedures that comprise Tracing API.
- Additionally, I've noticed that `(tag_v,tag_v)` eq and neq functions lacked the support function annotation, so I've added it.
> Internal documentation for tracing-related API.

- .github/workflows/docker.yaml
This reverts commit 1d6788b375834add73be4c1def2fd3f534c500fc.
> Revert "Temporarily use jg/autoupdate-timescaledb branch"

- CHANGELOG.md
- migration/incremental/027-tag-map-storage-views.sql
When we changed the storage type of `ps_trace.tag_map` and
`_ps_trace.tag_v` from `PLAIN` to `EXTENDED`, we didn't update all
`pg_attribute` entries. This meant that the definitions for our views
(`ps_trace.{event,link,span}`) were incorrect.
While we noticed this specifically with our views, it could also cascade
to tables or views which end users built on top of our types.
This change modifies the storage type for all `pg_attribute` entries of
type `ps_trace.tag_map` and `_ps_trace.tag_v`.
Note: should a user have purposefully set the storage type for a
specific column, this change will overwrite that. We deem this to be
very unlikely, and `EXTENDED` is almost certainly what you want.
> Correct storage type for columns deriving from `tag_map` and `tag_v`

- CHANGELOG.md
- sql/promscale--0.0.0.sql
The `prom_schema_migrations` table was not schema-qualified on creation,
so it could be in any schema. Find out the schema it's in and drop.
Part of: #371
> Correctly identify and drop `prom_schema_migrations`

- .github/workflows/ci.yaml
- .github/workflows/docker.yaml
- .github/workflows/lint.yaml
Our branch protection rules require that certain checks pass before
allowing a PR to be merged into the master branch.
Having `paths-ignore` set for these checks means that a PR which only
adds or touches a .md file will not have the required checks run, and so
is not able to be merged. This doesn't make sense.
> Remove `paths-ignore` for required CI workflows

- sql/promscale--0.0.0.sql
Follow-on change to https://github.com/timescale/promscale_extension/pull/372
The 0.0.0 script should only run if the prom_schema_migration table exists.
If we cannot find the table, raise an exception.
> Improve drop prom_schema_migration logic

- docs/sql-api.md
- migration/idempotent/001-base.sql
- migration/idempotent/011-maintenance.sql
- migration/incremental/028-refactor-mark-unused-series.sql
- Remove checks for timescaledb >= 2 in maintenance functions
- Fix indentation and typos
- Add some comments
- Refactor marking of unused series in context of dropping chunks
Rename `mark_unused_series` to `mark_series_to_be_dropped_as_unused`.
This clarifies that we're not finding series which are unused and
marking them for deletion. Instead, we are marking all of the series
which are only referenced by data in chunks which we will drop as
unused.
Move the `check_time` parameter in `drop_metric_chunks` to
`mark_series_to_be_dropped_as_unused`. The parameter is local to the
logic in `mark_series_to_be_dropped_as_unused`. It is an optimization
used to exclude series which are not unused from the
`get_confirmed_unused_series` check.
Note: As the calculation of `check_time` has been moved …
> Minor cleanup and refactoring

- CHANGELOG.md
- migration/idempotent/010-telemetry.sql
The intent of `promscale_metrics_ha_cluster_count` is to report number of prometheus HA clusters remote writing to promscale. Counting the `cluster` label[1] from `_prom_catalog.label` would do the job.
[1] https://github.com/timescale/promscale/blob/master/docs/high-availability/prometheus-HA.md#prometheus-leader-election-via-external-labels
Co-authored-by: James Guthrie <JamesGuthrie@users.noreply.github.com>
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
> Use `cluster` label from `_prom_catalog.label` to report about HA setup

- .github/workflows/docker.yaml
Root cause: GITHUB_TOKEN is authorized to push to ghcr only when it is run from the owner context.
Solution: Skip ghcr image push when CI is running on forked repo context.
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
> ci: skip docker push when PR is from forked repos

- Cargo.lock
- Cargo.toml
- docs/sql-api.md
- migration/idempotent/015-extension-function-permissions.sql
- src/lib.rs
- src/regex.rs
Postgres' native regex engine is a POSIX-compatible regex.
The regex engine used in Prometheus for PromQL is an RE2-based engine
[1], which is more like PCRE.
The re2_match function allows us to use promQL-compatible regexes in the
database.
[1]: https://swtch.com/~rsc/regexp/regexp3.html
> Add _prom_ext.re2_match(string, pattern) -> bool

- CHANGELOG.md
- migration/idempotent/010-telemetry.sql
Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>
Fixes: https://github.com/timescale/promscale/issues/1455
This PR optimises the `_ps_catalog.promscale_sql_telemetry()` by removing the `_bytes_total` metrics that were taking 95% of the time, sometimes even blocking for several minutes.
```postgres
tsdb=> select _ps_catalog.promscale_sql_telemetry_without_sizes(); -- This is the one proposed in the PR.
promscale_sql_telemetry_without_sizes 
---------------------------------------------
(1 row)
Time: 341.549 ms
tsdb=> select _ps_catalog.promscale_sql_telemetry(); // Previous function, taking forever.
```
> Remove `_bytes_total` calculations from telemetry.

- CHANGELOG.md
- Makefile
- alpine.Dockerfile
- create-upgrade-symlinks.sh
- extract-extension-version.sh
- ha.Dockerfile
We use `cargo pkgid`, plus some text transformation, to determine the
extension version.
In cargo 1.62.0 the output of `cargo pkgid` changed from:
`<...>#promscale:<ver>`
to:
`<...>#promscale@<ver>`
> Support cargo 1.62.0 pkgid format

- docs/sql-api.md
- e2e/testdata/create_ingest_temp_table.sql
- e2e/tests/snapshots/golden_tests__testdata__create_ingest_temp_table.sql.snap
- migration/idempotent/001-base.sql
- migration/incremental/029-remove-unused-ingest-func.sql
It can happen that we insert both samples and exemplars within the same
transaction. That means we need a separate temp table for these two 
so passing a prefix shoud help with that.
> Pass prefix for temporary table used for ingest

- .github/workflows/release.yaml
- CHANGELOG.md
- dist/deb.dockerfile
Ubuntu Hirsute became EOL in January 2022.
Debian Stretch became EOL at the end of June 2022. A glibc
incompatibility began to break our tests at approximately the same time,
so we are forced to drop support.
> Drop support for EOL distros

- Cargo.lock
- Cargo.toml
- alpine.Dockerfile
- e2e/Cargo.toml
- e2e/tests/dump-restore-test.rs
- e2e/tests/golden-tests.rs
- e2e/tests/test.rs
- gendoc/src/main.rs
- ha.Dockerfile
- test-common/Cargo.toml
- test-common/src/lib.rs
After we agreed to extract SQL tests into their own workspace, I've noticed we use `testcontainers` extensively and there's already a duplication between `gendoc` and `e2e`. In order to unify how we use them I extracted `common` module into its own workspace.
A prerequisite for #276 
> Extracting shared routines for interacting with postgresql testcontainer

- .github/workflows/docker.yaml
Docker images should be pushed on merging commits to the master branch.
The conditions introduced in f62b7ddb and e82da641 resulted in Docker
images not being pushed on master merges.
This change introduces a check on event type to ensure that the new
conditions are only applied to pull-request events.
> Ensure Docker push on merge commit

- CHANGELOG.md
- migration/idempotent/001-base.sql
- sql-tests/testdata/defaults.sql
- sql-tests/tests/snapshots/tests__testdata__defaults.sql.snap
Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>
Fixes: https://github.com/timescale/promscale/issues/1399
This PR does 2 things:
1. Makes the epoch duration (used in series cache on Promscale side) configurable
2. Increases the default duration to 12 hours. This will lead to fewer resets of cache and less transactional load, hence should help in improving metric ingest performance
> Adds ability to configure epoch duration

- CHANGELOG.md
- migration/idempotent/001-base.sql
- sql-tests/testdata/drop_metric.sql
- sql-tests/tests/snapshots/tests__testdata__drop_metric.sql.snap
Porting TestSQLDropMetricChunk from promscale into this repository because it mainly tests code that lives in this repository and is known to break when we simply change defaults. (See https://github.com/timescale/promscale/pull/1484)
One notable change between the original and this port is how the epoch is tested. This test just calls epoch_abort and asserts that it RAISEs an exception, while the original expects an actual ingestion failure.
Additionally, I fixed a minor bug in epoch_abort that caused a confusing message in RAISE.
> A port of TestSQLDropMetricChunk from promscale

- migration/incremental/030-remove-get-confirmed-unused-series.sql
This commit https://github.com/timescale/promscale_extension/commit/88416098bf4acb46dac936b58df93d934c4b9364 introduced a bug that prevents upgrading. We rename a parameter of the get_confirmed_unused_series function. This can't be done in `create or replace`. You have to drop the function first. This commit provides a migration that drops the function.
> drop the get_confirmed_unused_series function so we can rename a param

- .github/workflows/docker.yaml
When we added the automatic tagging and releasing of the
`timescaledev/promscale-extension` docker images, we forgot to tag the
`latest-ts2-pg<PGVER>`. This change fixes this for future releases.
> Tag and release `timescaledev/promscale-extension:latest-ts2-pg<PGVER>`

- .github/workflows/docker.yaml
Temporarily affixing `PREVIOUS_IMAGE` because 0.5.2 image was never tagged as `timescaledev/promscale-extension:latest-ts2-pg<PGVER>` 
See also https://github.com/timescale/promscale_extension/pull/422
> Temporarily affixing PREVIOUS_IMAGE for alpine image builds

- e2e/tests/test.rs
We would like to provide an upgrade path from 0.5.3 to 0.5.4, but it's
not possible to install version 0.5.3 because it's broken. The test
assumed that if it's possible to upgrade from a source version to a
target version, that it's also possible to install the source version.
> Ensure upgrade test only uses installable versions

- .github/workflows/docker.yaml
In commit c4b938bd we temporarily pinned the PREVIOUS_IMAGE setting to
work around a bug in how we pushed images to docker hub. This change
reverts that pin.
> Revert pinned PREVIOUS_IMAGE setting

- ha.Dockerfile
Ubuntu 21.10 is EOL, we can no longer build from it.
> Bump ha dockerfile base to Ubuntu 22.04

- CHANGELOG.md
- e2e/tests/ps_trace_delete_all_traces.rs
- migration/idempotent/008-tracing-functions.sql
- sql-tests/testdata/ps_trace.delete_all_traces.sql
- sql-tests/tests/snapshots/tests__testdata__ps_trace.delete_all_traces.sql.snap
The Promscale connector caches trace tags, schema_urls, operations, and
instrumentation_libs. If these values are removed from the database
while the connector is running, it will insert corrupted data.
Closes https://github.com/timescale/promscale/issues/1518.
> Prevent ps_trace.delete_all_traces() when Promscale connector running

- Makefile
- alpine.Dockerfile
The Makefile and alpine.Dockerfile needed the timescaledb version to be bumped to 2.7.2
> Build with timescaledb 2.7.2

- templates/incremental-wrapper.sql
The 001-extension.sql migration is expected to change. It references the versioned .so file which changes with each version. No need to warn about expected behavior.
> Remove unnecessary warning

- .github/workflows/release.yaml
- dist/rpm.dockerfile
The recently-released version 2.8.0 of the dotenv gem dropped support
for older ruby installations, which we're using on CentOS.
Ubuntu Impish is EOL, so we can't test our debian package on it.
> Fix release build

- dev.Dockerfile
Using lld instead of the default linker reduces recompile times when
only modifying SQL on an M1 mac from ~30s to ~2s.
> Use a faster linker in the devenv container

- .github/workflows/docker.yaml
- Cargo.toml
- DEVELOPMENT.md
- Makefile
- sql-tests/README.md
- sql-tests/testdata/create_ingest_temp_table.sql
- sql-tests/testdata/defaults.sql
- sql-tests/testdata/drop_metric.sql
- sql-tests/testdata/info_view.sql
- sql-tests/testdata/large_tracing_tags_support.sql
- sql-tests/testdata/metric-retention.sql
- sql-tests/testdata/ps_trace.delete_all_traces.sql
- sql-tests/testdata/support.sql
- sql-tests/testdata/tag_map.sql
- sql-tests/testdata/trace_compression.sql
- sql-tests/testdata/views.sql
- sql-tests/tests/snapshots/tests__testdata__defaults.sql.snap
- sql-tests/tests/snapshots/tests__testdata__info_view.sql.snap
- sql-tests/tests/snapshots/tests__testdata__large_tracing_tags_support.sql.snap
- sql-tests/tests/snapshots/tests__testdata__ps_trace.delete_all_traces.sql.snap
- sql-tests/tests/snapshots/tests__testdata__support.sql.snap
- sql-tests/tests/snapshots/tests__testdata__tag_map.sql.snap
- sql-tests/tests/snapshots/tests__testdata__trace_compression.sql.snap
- sql-tests/tests/snapshots/tests__testdata__views.sql.snap
- sql-tests/tests/tests.rs
- test-common/src/local_postgres_instance.rs
- test-common/src/test_container_instance.rs
This is a somewhat slow but safe and predictable way to run sql-tests against a set connection string instead of one-off docker containers.
Resolves #276 
> Dockerless SQL tests

- .github/workflows/docker.yaml
A fix for the third-party pull request CI path. `github.event.type` doesn't seem to be set to anything, thus `github.event.type != 'PullRequestEvent'` always evaluates to `true`.
> Another attempt at fixing CI for third party PRs

- INSTALL.md
- Makefile
This commit adds steps to build and install promscale extension on MacOS.
> Add steps to build on MacOS 

- migration/idempotent/001-base.sql
Due to a manual intervention to the database some tables or views for
metrics may be deleted. It's nice if `drop_metric` can still work in
this conditions and do a proper cleanup.
There was a previous attempt to pull it https://github.com/timescale/promscale_extension/pull/458.
The change looks minor and internal enough that it does not need to be communicated to end users.
> Don't fail metric deletion if some tables or views are missing

- CHANGELOG.md
- docs/sql-api.md
- migration/idempotent/001-base.sql
- sql-tests/testdata/metric-chunk-interval.sql
- sql-tests/tests/snapshots/tests__testdata__metric-chunk-interval.sql.snap
`SELECT prom_api.get_default_chunk_interval();` returns the current
default chunk interval for all metrics.
`SELECT prom_api.get_metric_chunk_interval(<metric name>);` returns the
chunk interval for the configured metric, or the default chunk interval
if not explicitly set.
> Add convenience functions for getting metric chunk interval

- CHANGELOG.md
- docs/sql-api.md
- migration/idempotent/007-tracing-tags.sql
- migration/incremental/031-remove-superfluous-tag_v-ops.sql
Fixes timescale/o11y-team-data-platform#56
We want to redefine the opclass for tag_v type to not use = operator.
This will improve type coercion for the typical use case.
Simply dropping the opclass should be safe since we don't expect anyone
to ever index using this opclass.
NOTE: We currently have two distinct types:
_ps_trace.tag_v and
ps_trace.tag_v
This is not ideal.
> Another attempt at fixing the bug with tag_v type

- Cargo.lock
- e2e/Cargo.toml
- e2e/tests/dump-restore-test.rs
- e2e/tests/incremental-freeze-test.rs
- e2e/tests/upgrade-test.rs
- e2e/tests/util/mod.rs
This change replaces usages of `println!()` with the logging-specific
macros (`info!()` and `debug!()`), allowing test execution logging to be
controlled.
To set the log level, set the RUST_LOG environment to one of `debug`,
`info`, etc.
> Use actual logging in dump-restore tests

- CHANGELOG.md
- sql/promscale--0.0.0.sql
It is possible that not all of these tables and views exist. For
instance if metric creation has not been finalized, or if there have not
yet been any samples ingested for a metric.
There are also degenerate cases in which tables which we expect to be
present are not present (e.g. `prom_data.<metric name>`). Being too
strict here results in our users having to do a bunch of cleanup.
Fixes https://github.com/timescale/promscale_extension/issues/473
> During upgrade from 0.3.x only alter relations which actually exist

- CHANGELOG.md
- docs/sql-api.md
- migration/idempotent/007-tracing-tags.sql
- sql-tests/testdata/tag_map.sql
- sql-tests/tests/snapshots/tests__testdata__tag_map.sql.snap
The _ps_trace.tag_v_text_eq_matching_tags matcher tests
equality for a tag_key to the textual representation of
the tag value. This means that a match for the string
"3" will match a jsonb string "3" or a jsonb int 3.
Please note: this does not yet handle the nested json
case.
> Add matcher for textual representation of json

- install-cargo-pgx.sh
Using the lock file ensures that we're not affected by breaking releases
imposed by transitive dependencies of cargo-pgx.
> Use Cargo.lock when installing cargo-pgx

- DEVELOPMENT.md
- e2e/scripts/load-data.sql
- e2e/scripts/snapshot.sql
- e2e/tests/incremental-freeze-test.rs
- e2e/tests/upgrade-test.rs
- migration/incremental/024-adjust_autovacuum.sql
- templates/incremental-wrapper.sql
Previously, the migration logic assumed the existance of a compressed hypertable. This is not the case when compression is disabled.
Solve this case and add tests.
Fixes #504 
> Fix migration when a metric is not compressed

- migration/idempotent/016-vacuum-engine.sql
- sql-tests/testdata/chunks_to_vacuum_freeze.sql
- sql-tests/tests/snapshots/tests__testdata__chunks_to_vacuum_freeze.sql.snap
Simplifies and fixes to the `_ps_catalog.chunks_to_freeze` view which identifies compressed chunks that are not fully frozen.
> Fix chunks_to_freeze

- .github/workflows/release.yaml
- Makefile
- tools/smoke-test
It used to be that we required the connector to smoke test the extension packages, because the extension could not be installed standalone. Since 0.5.0, this has been possible.
Using the connector to smoke test the installation causes problems when the connector is not compatible with the new extension version, which has happened when the extension minor version is incremented.
Fixes #516
> Remove Promscale connector from package smoke tests

- Cargo.lock
- test-common/Cargo.toml
- test-common/src/postgres_container/mod.rs
We've observed connection establishment failing numerous times in CI with "Connection reset by peer" (see [1], [2], [3]). For lack of a better alternative, I'm assuming that retrying it might fix the problem.
[1]: https://github.com/timescale/promscale_extension/issues/385#issuecomment-1226951114
[2]: https://github.com/timescale/promscale_extension/issues/385#issuecomment-1227213636
[3]: https://github.com/timescale/promscale_extension/issues/385#issuecomment-1248345194
> Add retry mechanism to connection creation in tests

- CHANGELOG.md
- migration/idempotent/001-base.sql
The logic in `_prom_catalog.delete_expired_series` mixed two unrelated concepts resulting in a bug.
Calling `delete_expired_series` should both:
1. Delete series belonging to the metric `metric_table` which have been marked for deletion, and which are old enough.
2. Increment the cache epoch every `epoch_duration`.
The bug meant that we would only delete the series (for one metric) if the cache epoch could also be incremented. This effectively meant that we would drop the expired series for one metric every `epoch_duration`.
This change ensures that expired series are always deleted, but the cache epoch is only incremented every `epoch_duration`.
> Correctly remove all expired series

- CHANGELOG.md
- migration/incremental/032-remove-non-empty-span-name-constraint.sql
Our tracing implementation is based on OTLP spec, though OTLP spec doesn't mandate span name to be non empty[1], we have a constraint in the _ps_trace.operation table which raises error on empty span name. On the other hand, Jaeger span name can be empty and their storage integration tests validates the same[2]. Jaeger author even suggested to remove[3] the constraint as it shouldn't trouble any part of the system.
[1] https://github.com/open-telemetry/opentelemetry-proto/blob/724e427879e3d2bae2edc0218fff06e37b9eb46e/opentelemetry/proto/trace/v1/trace.proto#L110-L121 
[2] https://github.com/jaegertracing/jaeger/blob/7872d1b07439c3f2d316065b1fd53e885b26a66f/plugin/storage/integration/fixtures/traces/default.json#L6 
[3] https://github.com/jaegertracing/jaeger/pull/3922#issuecomment-12565057 …
> Drop non empty span name check constraint from `_ps_trace.operation` table

- CHANGELOG.md
- build.rs
- templates/promscale.control
This change adds a `requires` entry to the extension control file,
making the `timescaledb` extension mandatory for installation.
We omit the `requires` entry when running `cargo pgx test`, because of
the (unnecessary) burden that it imposes on developer setup.
> Make timescaledb mandatory

- CHANGELOG.md
- migration/idempotent/001-base.sql
The temp table is currently created with ON COMMIT DROP, which requires that the temp table be recreated with each transaction. This incurs significant pg_catalog churn/bloat. With this change, the temp tables are created with ON COMMIT DELETE ROWS. This essentially truncates the table at the end of the transaction, but the table remains.
> Reuse ingestion temp tables across batches

- .github/workflows/ci.yaml
- .github/workflows/docker.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
Update github actions (where applicable) to avoid node12 warnings.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Some other actions have not yet been updated to node16.
> Bump Github Actions versions where applicable

- CHANGELOG.md
- docs/sql-api.md
- migration/idempotent/001-base.sql
- migration/incremental/033-metric-view.sql
- sql-tests/testdata/info_view.sql
- sql-tests/tests/snapshots/tests__testdata__info_view.sql.snap
`prom_info.metric` can be quite slow. Part of this is due to the columns that deal with disk size. Split the view into two views - one that does not have the size columns and is optimized for speed, and the original.
`prom_info.metric` is now a SQL view (not backed by a function) and it omits the columns dealing with disk size. On a test database containing 2,500 metrics and 1.5 million chunks, it returned in ~4 seconds whereas the original was killed after running for > 20 minutes.
`prom_info.metric_detail` is a view that is backed by a function (`_prom_catalog.metric_detail`) which has the same signature as the original view. i.e. it contains the columns dealing with disk size. If this is a multinode installation (which we don't currently even support), it executes the original query. …
> Optimize prom_info.metric view

- dev.Dockerfile
timescaledb-tune needs the `--profile=promscale` flag to provide the settings specifically tuned for promscale. This change supplies the flag in the devenv docker container.
> Run timescaledb-tune with promscale profile in devenv

- .gitignore
- misc/requirements.txt
- misc/tracegen.py
Moving the tracegen.py utility from the connector repo to the extension repo. It's a simple way to directly insert sample traces into the database. It was used during the development of the tracing schemas.
> Move tracegen from connector to extension repo

- CHANGELOG.md
- migration/idempotent/010-telemetry.sql
Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>
Implements `Number of active series` in https://github.com/timescale/promscale/issues/1616
> Add active_series and last_updated as telemetry

- sql-tests/testdata/chunks_to_freeze.sql
- sql-tests/tests/snapshots/tests__testdata__chunks_to_freeze.sql.snap
The calls to add_compression_policy can return different results depending on unrelated changes. This is causing folks to have to update this test's snapshot in PRs that have nothing to do with this test. This change fixes that issue.
> Make chunks to freeze test less finicky

- CHANGELOG.md
- docs/sql-api.md
- migration/idempotent/011-maintenance.sql
- migration/incremental/034-maintenance-job-stats.sql
- sql-tests/testdata/maintenance_jobs_separation.sql
- sql-tests/tests/snapshots/tests__testdata__chunks_to_freeze.sql.snap
- sql-tests/tests/snapshots/tests__testdata__maintenance_jobs_separation.sql.snap
When I started down the backend buffer approach, I didn't realize just how much transaction control happens in our background jobs. Carefully threading instrumentation through it proved an unreadable mess. But while doing so, I figured that separating maintenance jobs by type wouldn't require quite as big of a refactoring as I initially presumed and would allow us to implement 90% of what we wanted. E.g.
```SQL
SELECT
coalesce(config ->> 'signal', 'traces') AS signal_type,
coalesce(config ->> 'type', 'compression') AS job_type,
MAX(js.last_run_duration) AS last_duration,
SUM(js.total_failures) AS failures_count,
SUM(js.total_runs) AS total_runs_count
FROM timescaledb_information.job_stats js
JOIN timescaledb_information.jobs j ON j.job_id = js.job_id
WHERE proc_schema = '_prom_catalog' OR …
```
> Maintenance jobs metrics without backend local side channel

- .github/workflows/lint.yaml
This bumps to the newest version of pgspot, and installs it from pypi (with `pip`), which was not available when we integrated pgspot.
> Bump pgspot, install from pypi

- CHANGELOG.md
- migration/idempotent/001-base.sql
- sql-tests/testdata/get_label_key_column_name_for_view.sql
- sql-tests/tests/snapshots/tests__testdata__get_label_key_column_name_for_view.sql.snap
When creating a metric view, the column names for the labels are created by the `_prom_catalog.get_label_key_column_name_for_view` function. If a given label matches one of the reserved keys, then it's sanitized by prefixing the returned column name with `label_`, thus avoiding a conflict.
The `_prom_catalog.get_label_key_column_name_for_view` function also accepts a second argument, it's a boolean that if true means that the `id_column_name` should be used. The `id_column_name` is created as the label name with the `_id` suffix.
One of the reserved keys that's checked by
`_prom_catalog.get_label_key_column_name_for_view` is `series_id`. If the value `series` is given as argument the served key validation passes since `series != series_id`, and for `id=false` this continues to be correct, …
> Fix column "series_id" specified more than once

- .github/workflows/release.yaml
- dist/debian/lintian-ignore
It seems as though the Debian linter (Lintian) has new lints which fpm cannot fulfill, so we ignore the lints.
More details:
syntac-error-in-debian-changelog is for the generated `changelog.Debian.gz`, which is the standard fpm boilerplate Debian changelog. Somehow it still fails lintian.
package-contains-timestamped-gzip is a lint around reproducible builds, and fpm doesn't support reproducible builds [1].
[1]: https://github.com/jordansissel/fpm/issues/1232
> Fix package build

- migration/idempotent/017-metric-rollup.sql
- migration/idempotent/018-metric-rollup-maintenance.sql
- sql-tests/testdata/custom_downsample_refresh.sql
- sql-tests/testdata/metric_rollups_maintenance.sql
- sql-tests/testdata/metric_rollups_refresh.sql
- sql-tests/testdata/metric_rollups_scan_for_new_rollups.sql
- sql-tests/tests/snapshots/tests__testdata__custom_downsample_refresh.sql.snap
- sql-tests/tests/snapshots/tests__testdata__metric_rollups_refresh.sql.snap
- sql-tests/tests/snapshots/tests__testdata__metric_rollups_scan_for_new_rollups.sql.snap
This PR does 2 things:
1. Fixes the exception `Caggs already exists` that was caused when a cagg for one resolution was again created when the `scan_for_new_rollups()` was re-executed. Added a test under `metric_rollups_scan_for_new_rollups` to ensure correct behaviour.
2. `execute_caggs_compression_policy()` used to panic when looping over already compressed chunk of a Cagg that has some uncompressed chunks that need compression. Added rerunning compression policy to ensure correct behaviour.
> Fix: Exception when scanning for new rollups & compressing Caggs

- .github/workflows/release.yaml
In order to increase the reliability of our package build, we run the build nightly, and notify on Slack in case of failure.
> Run release build daily, and notify on failure

- migration/idempotent/001-base.sql
Clarify order of operations in `get_metrics_that_need_compression()`. A mixture of `AND`s and `OR`s made the code difficult to reason about. Fix it.
> Clarify order of operations in get_metrics_that_need_compression

- .github/workflows/ci.yaml
All matrix builds were using the same cache key, causing collisions.
pgx puts the postgres data directory in `target/pgx-test-data-<pg_ver>`,
which the `Swatinem/rust-cache` action cleans, by removing all its
content, and subsequently caches. This breaks pgx tests, which do not
expect the directory to be empty.
The combination of the cache collisions and incorrect caching caused a
number of build failures, which could only be fixed by removing the
cached artifacts from the GitHub cache.
> Fix ci test workflow

- dev.Dockerfile
Recent upgrade of pgx requires rust 1.64.0 which we missed in the dev.Dockerfile. Fixed here.
> Use rust 1.64.0 in devenv

- DEVELOPMENT.md
- dev.Dockerfile
We have identified issues with `make devenv` and `make docker-image-14` failing due to a signal 9 when cargo is building the `pgx-pg-sys` package. We believe this is due to RAM usage exceeding what docker is allowed. This PR limits cargo to using 2 jobs which in turn ought to reduce the RAM used.
> Make cargo use 2 jobs in devenv

- Makefile
- devenv.sh
Addressing a devenv footgun documented in https://github.com/timescale/promscale_extension/issues/585
- Firstly, I don't see a reason for make build to generate a versioned SQL
file in the first place. This action normally takes place during
the packaging step.
- Secondly, make clean and make devenv targets will be removing generated
files moving forward.
I didn't test this very exhaustively but it seems to help and I expect it to resolve #585
> Clean generated files on devenv (re)builds

- DEVELOPMENT.md
- Makefile
- devenv.sh
There may be situations when manually triggering rebuilds and reinstalls of the extension in the devenv container is preferred. This provides a `make devenv-no-entr` target to disable the automatic rebuilds/reinstalls.
The new `make dev-build` is used to trigger the rebuild/reinstall manually.
`make dev-bash` is handy to get a bash shell in the devenv container.
`make dev-psql` gets a psql shell into the devenv container.
> Support running devenv without entr

- CHANGELOG.md
- migration/idempotent/011-maintenance.sql
- migration/incremental/034-maintenance-job-stats.sql
- sql-tests/testdata/maintenance_jobs_separation.sql
It seems like 1 metric compression job is almost never enough and our benchmarks show that 3 should be sufficient for thousands of metrics with 30min chunks.
In addition, this PR addresses a thundering herd scenario when reconfiguring maintenance jobs.
> Increase the default number of compression jobs and prevent a "thundering herd" scenario

- migration/idempotent/001-base.sql
The connector uses this function to expose a prometheus metric and that part of the code is restricted to the prom_reader role.
> Grant execute on metric_chunks_that_need_to_be_compressed to prom_reader

- CHANGELOG.md
- migration/idempotent/016-vacuum-engine.sql
- migration/incremental/035-remove-func.sql
- sql-tests/testdata/vacuum_engine.sql
We have seen instances in which compresses chunks are missing statistics. Autovacuum ignores tables that are missing statistics. Analyzing these tables does not help since we rarely modify chunks after they are compressed. Therefore, these chunks are ignored until they pass the vacuum_freeze_max_age. This can be bad for performance. So, the vacuum engine makes a second pass looking for these chunks and vacuums them. We only use one worker for these.
See also: https://github.com/timescale/promscale/pull/1804
> Vacuum compressed chunks missing stats
