timescale/promscale_extension

Cargo.lock
Cargo.toml
Makefile

Also updates the makefile to auto-detect the postgres version.

Update with pg13 support

---

src/aggregates/vector_selector.rs

An instant vector query is defined by start == end and bucket_width == 0

Add support for instant vectors to vector_selector

---

Dockerfile

At some point in the future we will mark the extension as trusted, and
then we will be able to drop pgextwlist. In the meantime, the Promscale
test suite fails if pgextwlist is not present. By default, the test
suite runs against the `timescaledb-ha` docker image. This means that
until we have the trusted extension in `timescaledb-ha` we either need
to make Promscale able to handle either having pgextwlist, or trusted
extension. Adding pgextwlist back seems to be the simpler option.

Add back pgextwlist to built docker image

---

migration/idempotent/013-apply-config.sql

* dynamically discover func/proc to revoke execute from public
* dynamically discover tables to mark as config tables

Dynamically discover extension members

---

sql/promscale--0.0.0.sql

https://github.com/timescale/promscale_extension/issues/143

Add compressed hypertables backing the tracing tables to the extension

---

Cargo.lock
build.rs
migration/migration-table.sql
templates/migration-wrapper.sql

We emit a warning when detecting that the checksum has changed.

Store migration body in migration table

---

migration/migration/015-tracing-compression.sql
migration/migration/015-tracing-large-tags-fix.sql

Merging related migrations from two different preceding pull requests into one.

Merge 015 migrations

---

migration/migration/015-tracing-compression.sql

It seems that CHECK constrains come with a huge CPU
cost for the database. We can instead move checks to Promscale connector code.
Benchmarks show around 35% improvement in CPU usage.

Drop trace check contraints

---

build.rs

Migration files and idempotent filenames are prefixed with a number which determines the order in which they are combined during build. This commit checks these prefixes to ensure that there are no duplicate numbers present nor gaps in the numbering.

Prevent duplicate or missing numeric prefixes

---

Makefile
README.md
alpine.Dockerfile

Addresses #113 
Verified following a procedure, similar to the one described [here](https://github.com/timescale/timescaledb-docker-ha/pull/227#issuecomment-1101568154)

Simultaneous Promscale versions

---

sql/promscale--0.0.0.sql

Make sure that all objects made part of the extension are owned by
the object owner. Objects owned by someone else can easily be exploited
later. Do this automatically by traversing the depend tree.

Secure the takeover script

---

migration/incremental/015-tracing-compression.sql

As a follow-up to https://github.com/timescale/promscale/issues/748
In the future, should we decide to adopt a list or range partitioning scheme, the current tag table can [be converted into a default partition](https://github.com/timescale/promscale/issues/748#issuecomment-1109041670).

Re-creating tag table without partitions.

---

migration/incremental/015-tracing-redesign.sql

In the new tracing schema, prom_writer has select, insert, update, and delete.
It should only have select and insert.
Prom_modifier has no explicit privileges, but it should have select, insert, update, and delete.

Correct the privileges on tracing tables

---

templates/promscale.control

This was harder than I was expecting it to be. Open to other suggestions.

Update extension comment

---

Makefile
docs/sql-api.md
gendoc/src/main.rs

- Use local/dev_promscale_extension:head-ts2-pg14 image by default
- Make function sort ordering deterministic

Fixes for SQL API autogeneration

---

templates/promscale.control

Without this, the upgrade from 0.5.0 -> 0.5.1 is not possible.

Add "upgradeable_from" entry to ensure upgrade symlink is created

---

e2e/tests/test.rs

Add end-to-end test for version upgrade

---

.github/README.md
.github/workflows/docker.yaml
README.md

WARNING: Do not merge before https://github.com/timescale/promscale/pull/1402

Add e2e test from connector into CI

---

.github/workflows/docker.yaml

- ~[ ] CHANGELOG entry for user-facing changes~
- ~[ ] Updated the relevant documentation~

Fix the branch referenced by the embedded e2e workflow.

---

.github/workflows/docker.yaml

Bump TimescaleDB to 2.7.0 in docker workflow

---

.github/workflows/docker.yaml

Publish timescaledev/promscale-extension images in CI

---

CHANGELOG.md
Cargo.lock
Cargo.toml
e2e/tests/incremental-freeze-test.rs
migration/idempotent/014-extension-type-functions.sql
migration/incremental/001-extension.sql
sql/promscale--0.0.0.sql

Prepare 0.5.2 release

---

RELEASING.md

This change adds a checklist of steps to complete in order to release a
new version of the Promscale extension. The checklist can be copy-pasted
into a new GitHub issue to track the progress of each release.
Closes #35

Add RELEASING.md with release instructions

---

.github/workflows/README.md
.github/workflows/docker.yaml

- Renaming branch_name metadata variable, because it doesn't contain a vanilla branch name value.
- Make sure we always run e2e on the connector's master

Fixes for embedded e2e workflow

---

docs/sql-tracing-tables.md

The missing piece to resolve #159 -- a document that goes over relationships between tables from `_ps_trace` schema.

Tracing tables internals documentation

---

docs/sql-api.md
e2e/testdata/create_ingest_temp_table.sql
e2e/tests/snapshots/golden_tests__testdata__create_ingest_temp_table.sql.snap
migration/idempotent/001-base.sql
migration/idempotent/008-tracing-functions.sql

When ingesting we COPY into temporary tables to handle ON CONFLICT situations.
We need respective changes in Promscale connector.

Helper function to create temporary tables for ingest

---

.github/workflows/docker.yaml

It's not possible to both load and push, so we only do one or the other,
depending on whether the commit originated from a fork or not.

Either push to or load from docker registry

---

RELEASING.md

I have missed this in past releases. By adding it, it will hopefully not
be missed.

Add item to update extension tag in install instructions

---

DEVELOPMENT.md
Makefile
README.md
dev.Dockerfile
devenv.sh

This change adds a new docker-based long-lived developer environment.
Through the use of bind-mounting, hot-reloading, and locally-exposed
ports, you can edit sources locally and have them recompiled in the
container.

Add Docker-based development environment

---

CHANGELOG.md
Cargo.lock
Cargo.toml
INSTALL.md
e2e/tests/incremental-freeze-test.rs
migration/idempotent/014-extension-type-functions.sql
migration/incremental/001-extension.sql
sql/promscale--0.0.0.sql
templates/promscale.control

Prepare release 0.5.4

---

test-common/src/lib.rs

Some tests (upgrade tests) need to use specific docker images. Modifies the PostgresTestHarness to allow tests to specify the docker image to be used. Also changes the default docker image to the "local" image. When developing, this is most likely the image you want to be running tests against.

Allow tests to specify docker image

---

.github/workflows/docker.yaml

Bump timescaledb version to 2.7.2

---

DEVELOPMENT.md

We have a number of different ways to test code in this repository, and
it's not immediately obvious which to use. This guidance should help
developers be aware of their choices, and make the right choice.
Closes #383.

Add guidance on testing methods

---

Cargo.lock
RELEASING.md
e2e/Cargo.toml
e2e/tests/config/mod.rs
e2e/tests/upgrade-test.rs
test-common/src/postgres_container/mod.rs

This change ensures that we simulate the way that our users will upgrade
the extension, using our publically-published canonical images.

Run upgrade tests across released Docker containers

---

e2e/tests/test.rs

Print actual DB error in upgrade_promscale_extension_all_versions

---

INSTALL.md

Update OSX build instruction

---

migration/idempotent/010-telemetry.sql

This commit adds a telemetry event named `promscale_traces_jaeger_span_types` to find types of jaeger spans ingested into promscale.
Fixes https://github.com/timescale/promscale/issues/1548
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>

Add telemetry event to find jaeger span ingestion

---

CHANGELOG.md
Cargo.lock
Cargo.toml
INSTALL.md
e2e/tests/incremental-freeze-test.rs
migration/idempotent/014-extension-type-functions.sql
migration/incremental/001-extension.sql
sql/promscale--0.0.0.sql
templates/promscale.control

Preparing for the 0.6.0 release.

Prepare release 0.6.0

---

RELEASING.md

If we have an issue, then everybody knows what the status of the ongoing
release is.

Update RELEASING instructions

---

RELEASING.md

Updated RELEASING.md to be more explicit, correct a few omissions, etc.

Updating releasing instructions

---

RELEASING.md
build.rs
e2e/tests/incremental-freeze-test.rs
migration/idempotent/014-extension-type-functions.sql
migration/incremental/001-extension.sql
templates/promscale--0.0.0.sql
update-version.sh

Automate bumping extension version across multiple files

---

Makefile

Create promscale.control file when running `make devenv`

---

dev.Dockerfile

Pin timescaledb to 2.7.2 in devenv container

---

test-common/src/postgres_container/mod.rs

Add exponential backoff to retry mechanism in tests

---

CHANGELOG.md
Cargo.lock
Cargo.toml
INSTALL.md
e2e/tests/incremental-freeze-test.rs
sql/promscale--0.6.0.sql
update-version.sh

Release 0.7.0

---

docs/sql-tracing-tables.md

Minor fixes to markdown format

Fix docs markdown format

---

.github/workflows/docker.yaml
Makefile
alpine.Dockerfile
dev.Dockerfile
e2e/scripts/post-restore.sql
e2e/scripts/snapshot.sql
e2e/tests/config/mod.rs
e2e/tests/dump-restore-test.rs
e2e/tests/upgrade-test.rs
sql-tests/testdata/tag_map.sql
sql-tests/tests/snapshots/tests__testdata__tag_map.sql.snap

Bump TimescaleDB to 2.8.0

---

.github/workflows/lint.yaml
.github/workflows/release.yaml
Cargo.lock
Cargo.toml
Makefile
alpine.Dockerfile
devenv.sh
e2e/Cargo.toml
gendoc/Cargo.toml
ha.Dockerfile
install-cargo-pgx.sh
sql-tests/Cargo.toml
sql-tests/tests/tests.rs
src/aggregates/gapfill_delta.rs
src/aggregates/prom_delta.rs
src/aggregates/prom_increase.rs
src/aggregates/prom_rate.rs
src/aggregates/vector_selector.rs
src/iterable_jsonb.rs
src/jsonb_digest.rs
src/palloc.rs
src/raw.rs
src/regex.rs
src/support.rs
src/type_builder.rs
src/util.rs

Waiting on PR to be merged upstream [1].
[1]: https://github.com/tcdi/pgx/pull/716

Upgrade to pgx 0.5.4

---

.github/workflows/ci.yaml
.github/workflows/docker.yaml
.github/workflows/lint.yaml
.github/workflows/release.yaml

GitHub deprecated some patterns which we use in our own, and in dependent GitHub Actions.

Update GitHub Actions

---

.github/workflows/release.yaml

Only notify on failed release once

---

.github/workflows/release.yaml

Fix broken release build notification

---

Cargo.lock
Cargo.toml
install-cargo-pgx.sh

Pretty much what's in the title

Minor dependency updates

---

dist/rpm.dockerfile

An attempt to fix release workflow for rockylinux

---

CHANGELOG.md
Cargo.lock
Cargo.toml
e2e/tests/incremental-freeze-test.rs

Preparing release 0.8.0

---

.github/workflows/release.yaml

Disable scheduled release build and notification
